# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger: none
pr: none

schedules:
- cron: 0 3 * * Mon-Fri
  displayName: Daily Automated Test Run
  branches:
    include:
    - main
  always: true

pool: DEFRA-COMMON-ubuntu2004-SSV3

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: AzureCLI@2
  inputs:
    azureSubscription: AZD-RWD-DEV1
    scriptType: bash
    scriptLocation: inlineScript 
    inlineScript: |
      npm install
      npx wdio ./config/wdio.azure.dev4.conf.ts --suite Landing_Pages -secrets $(keyVaultUrlDev)
  displayName: 'npm install and run tests'

- task: PublishCucumberReport@1
  inputs:
    jsonDir: '$(System.DefaultWorkingDirectory)/report'
    outputPath: '$(System.DefaultWorkingDirectory)/report'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true
    name: $(Build.BuildNumber)
    title: $(Build.DefinitionName)
  displayName: Publish report
  condition: always()