export type ComplianceSchemes =
  | "Beyondly"
  | "Beyondly (NIEA)"
  | "Biffpack"
  | "BiffPack (NIEA)"
  | "Co2 Compliance (NIEA)"
  | "Co2 Compliance (SEPA)"
  | "Comply with Clarity"
  | "Comply with Clarity (NIEA)"
  | "ComplyPak"
  | "ComplyPak (NIEA)"
  | "Ecosurety (EA)"
  | "Ecosurety (NIEA)"
  | "Ecosurety Scotland (SEPA)"
  | "Enpack"
  | "ERP (NIEA)"
  | "ERP UK Ltd"
  | "Ethical Compliance"
  | "Kite Environmental Solutions"
  | "Kite Environmental Solutions (NIEA)"
  | "Leafpak"
  | "Leafpak (NIEA)"
  | "Packcare"
  | "Paperpak"
  | "Paperpak (NIEA)"
  | "Pennine-Pack"
  | "Pennine-Pack (Northern Ireland Environment Agency)"
  | "Recycle Wales (NRW)"
  | "Recycling Lives Compliance Services"
  | "Recycling Lives Compliance Services (NIEA)"
  | "REPIC"
  | "REPIC (NIEA)"
  | "Scotpak (SEPA)"
  | "Smart Comply (EA)"
  | "Smart Comply (NIEA)"
  | "Synergy Compliance"
  | "Synergy Compliance (Northern Ireland Environment Agency)"
  | "Valpak"
  | "Valpak (NIEA)"
  | "Valpak Scotland Ltd (SEPA)"
  | "Veolia (EA)"
  | "Veolia (NIEA)"
  | "Veolia (SEPA)"
  | "Wastepack (EA)"
  | "Wastepack GB (SEPA)"
  | "Wastepack UK (NIEA)"