export enum HeadersInEnglish {
  TitleEngland = "Large producers on 'report packaging data' for England",
  TitleWales = "Large producers on 'report packaging data' for Wales",
  TitleScotland = "Large producers on 'report packaging data' for Scotland",
  TitleNorthernIreland = "Large producers on 'report packaging data' for Northern Ireland",
  TitleAllNations = "Large producers on 'report packaging data' for all Home Nations",
  Header1 = "Environmental regulator",
  Header2 = "Reporting year",
  Header3 = "Organisation name",
  Header4 = "Trading name",
  Header5 = "Companies House number",
  Header6 = "RPD Organisation ID",
  Header7 = "Subsidiary ID",
  Header8 = "Address line 1",
  Header9 = "Address line 2",
  Header10 = "Address line 3",
  Header11 = "Address line 4",
  Header12 = "Town",
  Header13 = "County",
  Header14 = "Country",
  Header15 = "Postcode",
  Header16 = "Compliance scheme",
  Header17 = "Compliance scheme regulator",
}

export enum HeadersInWelsh {
  TitleEngland = "Cynhyrchwyr mawr ar 'Rhoi gwybod am ddata pecynwaith' ar gyfer Lloegr",
  TitleWales = "Cynhyrchwyr mawr ar 'Rhoi gwybod am ddata pecynwaith' ar gyfer Cymru",
  TitleScotland = "Cynhyrchwyr mawr ar 'Rhoi gwybod am ddata pecynwaith' ar gyfer yr Alban",
  TitleNorthernIreland = "Cynhyrchwyr mawr ar 'Rhoi gwybod am ddata pecynwaith' ar gyfer Gogledd Iwerddon",
  TitleAllNations = "Cynhyrchwyr mawr ar y gwasanaeth 'Rhoi gwybod am ddata pecynwaith' ar gyfer holl genhedloedd y Deyrnas Unedig",
  Header1 = "Rheoleiddiwr amgylcheddol",
  Header2 = "Blwyddyn adrodd",
  Header3 = "Enw'r sefydliad",
  Header4 = "Enw masnachu",
  Header5 = "Rhif y cwmni",
  Header6 = "ID sefydliad RPD",
  Header7 = "ID atodol",
  Header8 = "Llinell 1 y cyfeiriad",
  Header9 = "Llinell 2 y cyfeiriad",
  Header10 = "Llinell 3 y cyfeiriad",
  Header11 = "Llinell 4 y cyfeiriad",
  Header12 = "Tref",
  Header13 = "Sir",
  Header14 = "Gwlad",
  Header15 = "Cod post",
  Header16 = "Cynllun cydymffurfio",
  Header17 = "Rheoleiddiwr y cynllun cydymffurfio",
}
